'use client';
import {useState} from 'react';
const sets={Day:[24,22,28,34,32,40,37,46,52,48,58,64,60,69,76,82],Week:[18,22,20,28,35,32,48,54,45,62,58,72,68,78,74,82],Month:[42,38,34,46,40,48,55,51,64,58,54,68,62,70,78,74]};
const signalCards=[{icon:'↯',tone:'amber',label:'Earthquakes',value:'137',unit:'past 24 hours',tag:'Above typical',text:'Most are tiny—too small to feel—but clusters can show rock breaking as magma moves.'},{icon:'↟',tone:'red',label:'Ground movement',value:'+3.8',unit:'cm this month',tag:'Rising',text:'GPS instruments show the summit swelling. Scientists call this inflation.'},{icon:'≋',tone:'blue',label:'Sulfur dioxide',value:'1,240',unit:'tonnes per day',tag:'Steady',text:'Gas escapes from magma. A fast change can matter more than a single high reading.'}];
export default function Home(){const [range,setRange]=useState<keyof typeof sets>('Week');const [modal,setModal]=useState(false);const [shared,setShared]=useState(false);const share=async()=>{try{if(navigator.share)await navigator.share({title:'Kīlauea Watch',text:'Volcano activity made clear',url:location.href});else await navigator.clipboard.writeText(location.href);setShared(true);setTimeout(()=>setShared(false),1800)}catch{}};return <main className="shell">
<nav className="nav"><a className="brand" href="#top"><span className="brandMark">K</span><span>Kīlauea Watch</span></a><div className="navLinks"><a href="#activity">Activity</a><a href="#signals">Signals</a><a href="#learn">Learn</a><a href="#sources">Sources</a></div><button className="share" onClick={share}>{shared?'Link copied ✓':'Share tracker'}</button></nav>
<section className="hero" id="top"><div><p className="eyebrow"><span className="liveDot"/> Kīlauea summit · learning dashboard</p><h1>What is the volcano<br/><em>telling us?</em></h1><p className="intro">A clear, calm view of Kīlauea’s signals—made for everyone. Explore what scientists watch and what the trends may mean.</p><div className="heroNote"><b>Good to know</b><span>This prototype uses clearly marked demonstration data. For safety decisions, always follow USGS HVO and Hawaiʻi County.</span></div></div><div className="statusCard"><div className="statusTop"><span>Illustrative signal level</span><span className="updated">DEMO · NOT LIVE</span></div><div className="signal"><span className="signalRing"><i/></span><div><strong>Elevated</strong><small>Several example signals are above baseline</small></div></div><div className="meter"><i/></div><div className="meterLabels"><span>Quiet</span><span>Changing</span><span>Strong</span></div></div></section>
<section className="forecastStrip"><div><span className="forecastIcon">≈</span><p><b>Short-term eruption outlook</b><br/><small>These example signals would suggest a <strong>heightened chance</strong> of activity—but no dashboard can tell the exact day or hour.</small></p></div><button onClick={()=>setModal(true)}>How this works <span>→</span></button></section>
<section className="dashboard" id="activity"><article className="chartCard"><header><div><p className="kicker">Earthquakes & tremor</p><h2>The volcano is getting noisier</h2></div><div className="ranges">{(Object.keys(sets) as (keyof typeof sets)[]).map(r=><button key={r} onClick={()=>setRange(r)} className={range===r?'active':''}>{r}</button>)}</div></header><div className="chartWrap"><div className="ylabels"><span>High</span><span>Typical</span><span>Low</span></div><div className="barChart" aria-label={`Illustrative tremor trend for ${range}`}>{sets[range].map((v,i)=><i key={i} style={{height:`${v}%`}} title={`Relative signal ${v}`}/>)}</div></div><footer><span>{range==='Day'?'Midnight':range==='Week'?'7 days ago':'30 days ago'}</span><span>Now</span></footer><p className="plain"><b>In plain language:</b> Small earthquakes and continuous shaking called tremor are increasing in this example. This can happen when magma or gas moves underground.</p></article><aside className="stack"><article className="metricCard"><div className="metricHead"><span className="icon amber">↟</span><span className="trend up">Rising</span></div><p className="kicker">Summit inflation</p><strong className="metric">+3.8 <small>cm</small></strong><p>The ground is swelling, like a balloon slowly filling.</p><div className="spark">{[18,22,21,30,34,38,46,52,58,67].map((v,i)=><i key={i} style={{height:v}}/>)}</div></article><article className="metricCard"><div className="metricHead"><span className="icon blue">≋</span><span className="trend steady">Steady</span></div><p className="kicker">Sulfur dioxide</p><strong className="metric">1,240 <small>t/day</small></strong><p>Example gas output is above background, but not accelerating.</p></article></aside></section>
<section className="signalsSection" id="signals"><div className="sectionTitle"><p className="kicker">The signal board</p><h2>Three clues, one bigger story</h2><p>No single measurement predicts an eruption. Scientists look for several signals changing together.</p></div><div className="signalGrid">{signalCards.map(c=><article key={c.label}><div className={`icon ${c.tone}`}>{c.icon}</div><p className="kicker">{c.label}</p><strong>{c.value}</strong><small>{c.unit}</small><span className="tag">{c.tag}</span><p>{c.text}</p></article>)}</div></section>
<section className="learn" id="learn"><div><p className="kicker">Volcano forecast 101</p><h2>Prediction is more like a weather forecast than a countdown.</h2><p>Scientists compare today’s signals with Kīlauea’s past behavior. When earthquakes, swelling, gas, and heat rise together, concern can increase. But magma may stall, drain away, or change course.</p><button onClick={()=>setModal(true)}>See the 4-step method</button></div><div className="forecastScale"><p><b>How to read the outlook</b></p>{[['Low','Signals near baseline'],['Watch','One or more signals changing'],['Heightened','Several signals rising together'],['Imminent','Strong evidence eruption may be very near']].map((x,i)=><div key={x[0]}><span className={`level l${i}`}>{i+1}</span><p><b>{x[0]}</b><small>{x[1]}</small></p></div>)}<em>Only official scientists issue real alerts.</em></div></section>
<section className="safety"><span>!</span><div><p className="kicker">When it matters</p><h2>Use official alerts for real-world decisions.</h2><p>Conditions around Kīlauea can change quickly. This educational tracker does not replace evacuation notices, closures, air-quality guidance, or USGS volcano alerts.</p></div><a href="https://www.usgs.gov/volcanoes/kilauea/volcano-updates" target="_blank" rel="noreferrer">Open USGS updates ↗</a></section>
<footer className="footer" id="sources"><div className="brand"><span className="brandMark">K</span><span>Kīlauea Watch</span></div><p>Built to make volcano science understandable—not to replace scientists.</p><div><a href="https://www.usgs.gov/volcanoes/kilauea" target="_blank" rel="noreferrer">USGS Kīlauea</a><a href="https://www.ready.gov/volcanoes" target="_blank" rel="noreferrer">Volcano safety</a></div></footer>
{modal&&<div className="modalShade" onClick={()=>setModal(false)}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="method" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)} aria-label="Close">×</button><p className="kicker">Behind the outlook</p><h2 id="method">How scientists estimate what may happen next</h2><ol><li><b>Measure</b><span>Seismometers, GPS, gas sensors, cameras, and satellites collect clues.</span></li><li><b>Compare</b><span>Experts compare current patterns with the volcano’s own history.</span></li><li><b>Combine</b><span>Multiple clues agreeing is more meaningful than one unusual reading.</span></li><li><b>Communicate uncertainty</b><span>Forecasts describe likelihood and confidence—not an exact appointment.</span></li></ol><p className="modalWarn"><b>Important:</b> The values on this prototype are demonstration data and do not describe current conditions.</p></section></div>}
</main>}
