'use client';
import {useEffect,useMemo,useState} from 'react';
import {alertTone,colorTone,fmtTime,histogram,MONITORING_URL,NOTICE_URL,parseQuakes,parseStatus,rangeDays,STATUS_URL,tiltPlots,webcams,type Range} from '../src/monitoring';
import {useFeed} from '../src/useFeed';
import {Briefing,ThermalView,TimeMachine} from '../src/Discovery';

export default function Home(){
  const [range,setRange]=useState<Range>('Day');
  const [refresh,setRefresh]=useState(0);
  const [windowEnd,setWindowEnd]=useState(()=>Date.now());
  const [camera,setCamera]=useState(0);
  const [play,setPlay]=useState(false);
  const [plot,setPlot]=useState(0);
  const [plotError,setPlotError]=useState(false);
  const [plotLoaded,setPlotLoaded]=useState(false);
  const [shareMessage,setShareMessage]=useState('');
  const refreshAll=()=>{setWindowEnd(Date.now());setRefresh(n=>n+1);setPlotError(false);setPlotLoaded(false);};
  useEffect(()=>{const timer=setInterval(()=>{setWindowEnd(Date.now());setRefresh(n=>n+1);setPlotError(false);setPlotLoaded(false);},300000);return()=>clearInterval(timer)},[]);
  const windowStart=windowEnd-rangeDays[range]*86400000;
  const quakeUrl=`https://earthquake.usgs.gov/fdsnws/event/1/query?format=geojson&latitude=19.421&longitude=-155.287&maxradiuskm=30&starttime=${encodeURIComponent(new Date(windowStart).toISOString())}&endtime=${encodeURIComponent(new Date(windowEnd).toISOString())}&orderby=time&limit=20000`;
  const statusFeed=useFeed(STATUS_URL,parseStatus,refresh);
  const quakeFeed=useFeed(quakeUrl,parseQuakes,refresh);
  const status=statusFeed.data;
  const quakes=quakeFeed.data;
  const bins=useMemo(()=>histogram(quakes||[],windowStart,windowEnd),[quakes,windowStart,windowEnd]);
  const maxBin=Math.max(1,...bins.map(b=>b.count));
  const latest=quakes?.[0];
  const aviation=colorTone(status?.colorCode);
  const alert=alertTone(status?.alertLevel);
  const statusLabel=statusFeed.stale?'CACHED · CHECK SOURCE':statusFeed.loading?'CHECKING':status?'USGS STATUS':'UNAVAILABLE';
  const quakeLabel=quakeFeed.stale?'CACHED':quakeFeed.loading?'CHECKING':quakes?'USGS CATALOG':'UNAVAILABLE';
  const plotUrl=`https://volcanoes.usgs.gov/vsc/captures/kilauea/${tiltPlots[plot].file}?refresh=${Math.floor(windowEnd/300000)}`;
  const selectedCam=webcams[camera];
  const share=async()=>{try{if(navigator.share){await navigator.share({title:'Kīlauea Watch',url:location.href});setShareMessage('Shared');}else{await navigator.clipboard.writeText(location.href);setShareMessage('Link copied');}}catch(e){if(!(e instanceof Error&&e.name==='AbortError'))setShareMessage('Copy the page address from your browser to share.');}};
  return <main className="shell">
    <a href="#activity" className="skipLink">Skip to monitoring data</a>
    <nav className="nav"><a className="brand" href="#top"><span className="brandMark">K</span><span>Kīlauea Watch</span></a><div className="navLinks"><a href="#activity">Earthquakes</a><a href="#inflation">Inflation</a><a href="#cameras">Cameras</a><a href="#learn">Learn</a></div><button className="share" onClick={share}>Share tracker</button></nav>
    <nav className="sectionNav" aria-label="Jump to a section"><a href="#briefing">Briefing</a><a href="#activity">Earthquakes</a><a href="#inflation">Inflation</a><a href="#cameras">Live cameras</a><a href="#thermal">Thermal & replay</a><a href="#history">Time machine</a></nav>
    {shareMessage&&<p role="status">{shareMessage}</p>}
    <section className="hero" id="top"><div><p className="eyebrow">Kīlauea summit · official sources</p><h1>What is the volcano<br/><em>telling us now?</em></h1><p className="intro">USGS status, nearby earthquakes, summit tilt, and cameras—made understandable, without pretending to predict an exact eruption time.</p><div className="heroNote liveNote"><b>FEED HEALTH</b><div aria-live="polite"><p>Volcano status: {statusFeed.error?`unavailable${status?' · last successful reading retained':''}`:statusFeed.loading?'checking…':'connected'}{statusFeed.checked&&` · checked ${fmtTime(statusFeed.checked)}`}</p><p>Earthquakes: {quakeFeed.error?'unavailable':quakeFeed.loading?'checking…':'connected'}{quakeFeed.checked&&` · checked ${fmtTime(quakeFeed.checked)}`}</p><small>Checks every 5 minutes. Source reports and measurements may be older.</small></div><button onClick={refreshAll}>Refresh data</button></div></div>
      <div className={`statusCard status-${alert}`}><div className="statusTop"><span>Official volcano alert</span><span className="updated">{statusLabel}</span></div><div className="signal"><span className={`statusDot status-${alert}`} aria-hidden="true">●</span><div><strong>{status?.alertLevel||'Unknown'}</strong><small>{status?`Aviation color: ${status.colorCode}`:'No official reading available yet'}</small></div></div><p className="sourceTime">Status timestamp: {status?fmtTime(status.alertDate):'—'}</p><p className="sourceTime">An alert is not an eruption countdown. Unknown does not mean normal.</p></div>
    </section>
    <Briefing status={status} stale={statusFeed.stale} quakes={quakes} quakeStale={quakeFeed.stale} range={range} start={windowStart} end={windowEnd}/>

    <section className="dashboard" id="activity"><article className="chartCard"><header><div><p className="kicker">Earthquake counts · 30 km around summit</p><h2>{quakes!==null?`${quakes.length.toLocaleString()} nearby earthquakes`:quakeFeed.error?'Earthquake feed unavailable':'Loading earthquake counts…'}</h2><small>{quakeLabel} · selected {range.toLowerCase()}</small></div><div className="ranges" aria-label="Earthquake time window">{(['Day','Week','Month'] as Range[]).map(r=><button key={r} onClick={()=>setRange(r)} aria-pressed={range===r} className={range===r?'active':''}>{r}</button>)}</div></header>
      {quakes!==null?<><div className="chartWrap"><div className="ylabels"><span>{maxBin}</span><span>Count</span><span>0</span></div><div className="barChart" role="img" aria-label={`${quakes.length} earthquakes in 16 equal time intervals; exact counts in table below`}>{bins.map((b,i)=><i key={i} style={{height:`${b.count/maxBin*100}%`}} title={`${fmtTime(b.start)} – ${fmtTime(b.end)}: ${b.count} earthquakes`}/>)}</div></div><footer><span>{fmtTime(windowStart)}</span><span>{fmtTime(windowEnd)}</span></footer><details className="dataTable"><summary>View exact counts and times</summary><table><caption>Equal time intervals, all times HST</caption><thead><tr><th>From</th><th>To</th><th>Count</th></tr></thead><tbody>{bins.map((b,i)=><tr key={i}><td>{fmtTime(b.start)}</td><td>{fmtTime(b.end)}</td><td>{b.count}</td></tr>)}</tbody></table></details></>:<p className="emptyState">{quakeFeed.error?'The catalog could not be reached. No earthquake counts are being assumed.':'Requesting USGS earthquake observations…'}</p>}
      {quakes&&quakes.length>=20000&&<p role="status">Catalog limit reached: this view may omit older events. Choose a shorter window.</p>}
      <p className="plain"><b>How to read it:</b> Taller bars mean more recorded earthquakes in that interval—not a greater measured eruption probability. Zero-height bars mean zero events. The scale changes with the selected window; there is no established “typical” line here. Nearby events can include non-volcanic earthquakes, and the preliminary catalog may be revised.</p></article>
      <aside className="stack"><article className="metricCard"><div className="metricHead"><span className="icon amber" aria-hidden="true">↯</span><span className="updated">{quakeLabel}</span></div><p className="kicker">Latest earthquake in selected window</p><strong className="metric">{latest?.properties.mag!=null?`M${latest.properties.mag.toFixed(1)}`:'—'}</strong><p>{latest?`${latest.properties.place} · ${fmtTime(latest.properties.time)}`:quakes?'No recorded events in this window.':'No data available yet.'}</p>{latest&&<a className="dataLink" href={latest.properties.url} target="_blank" rel="noreferrer">Event details ↗</a>}</article><article className={`metricCard status-${aviation}`}><div className="metricHead"><span className={`icon status-${aviation}`} aria-hidden="true">●</span><span className="updated">{statusLabel}</span></div><p className="kicker">Aviation color</p><strong className="metric">{status?.colorCode||'Unknown'}</strong><p>The icon follows the official color code. Gray means unknown or unassigned—not green.</p></article></aside>
    </section>

    <section className="inflationSection" id="inflation"><div className="sectionTitle"><p className="kicker">Magma storage clues · USGS station UWD</p><h2>Is the summit inflating?</h2><p>Watch the official ground-tilt plot below. Tilt measures tiny changes in ground angle in microradians—not centimeters of ground rise.</p></div><article className="chartCard tiltCard"><header><div><h3>Summit tilt · Uēkahuna (UWD)</h3><small>USGS-hosted plot · read its latest measurement time on the image</small></div><div className="ranges" aria-label="Tilt time window">{tiltPlots.map((p,i)=><button key={p.file} aria-pressed={plot===i} className={plot===i?'active':''} onClick={()=>{setPlot(i);setPlotError(false);setPlotLoaded(false);}}>{p.label}</button>)}</div></header>{!plotLoaded&&!plotError&&<p role="status">Loading the official tilt plot…</p>}{!plotError&&<a href={plotUrl} target="_blank" rel="noreferrer" aria-label="Open full-size USGS tilt plot"><img key={plotUrl} className="tiltPlot" src={plotUrl} alt={`USGS UWD radial and tangential ground tilt over ${tiltPlots[plot].label}; see the plotted axes, legend, and timestamps for measurements`} onLoad={()=>setPlotLoaded(true)} onError={()=>setPlotError(true)}/></a>}{plotError&&<p role="status">The plot could not load. <a href={MONITORING_URL} target="_blank" rel="noreferrer">Open the official monitoring page instead ↗</a></p>}<p className="sourceTime">This image is served by USGS, not a simulated graph. Reloading it does not guarantee a new measurement; check the dates on the plot.</p><a className="dataLink" href={MONITORING_URL} target="_blank" rel="noreferrer">USGS monitoring data and instrument notes ↗</a></article>
      <div className="inflationGuide"><article><span>↗</span><h3>Rising radial tilt</h3><p>At this station’s current orientation, a rising radial trace can indicate inflation: pressure or magma accumulating beneath the summit.</p></article><article><span>↘</span><h3>Falling radial tilt</h3><p>A falling trace can indicate deflation. This can happen as magma leaves storage during an eruptive episode or moves elsewhere.</p></article><article><span>≈</span><h3>Forecast clue, not a timer</h3><p>HVO compares the pattern and rate with earlier episodes and other observations. Rain, instrument problems, and changing magma pathways can alter the signal. Inflation does not guarantee an eruption.</p></article></div><p className="sourceTime">Interpretation: <a href={MONITORING_URL} target="_blank" rel="noreferrer">USGS monitoring guidance</a>. For an actual forecast window, use the latest HVO notice above.</p>
    </section>

    <section className="cameraSection" id="cameras"><div className="sectionTitle"><p className="kicker">Official USGS summit cameras</p><h2>A live look, from three angles</h2><p>Choose a camera, then play it here or open its official YouTube stream. USGS may replace stream IDs; the “Open current stream” link follows the permanent USGS redirect.</p></div><div className="cameraLayout"><div><div className="videoFrame">{play?<iframe key={selectedCam.id} src={`https://www.youtube.com/embed/${selectedCam.id}?autoplay=1&mute=1&rel=0`} title={`${selectedCam.code} ${selectedCam.label} USGS camera`} referrerPolicy="strict-origin-when-cross-origin" allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen/>:<div className="videoPlaceholder"><span aria-hidden="true">▶</span><h3>{selectedCam.label}</h3><p>{selectedCam.code} · {selectedCam.detail}</p><button onClick={()=>setPlay(true)}>Play selected camera</button><small>Loads a YouTube player. Playback may be restricted by your browser.</small></div>}</div><div className="cameraActions"><a className="outlookLink" href={selectedCam.url} target="_blank" rel="noreferrer">Open current {selectedCam.code} stream on YouTube ↗</a>{play&&<button onClick={()=>setPlay(false)}>Close player</button>}</div><p className="sourceTime">If the player says unavailable, use the current-stream link. We cannot verify continuous playback. Streams checked August 27, 2026; clouds, darkness, and outages can interrupt views.</p></div><div className="cameraPicker">{webcams.map((cam,i)=><button key={cam.code} onClick={()=>{setCamera(i);setPlay(false);}} aria-pressed={camera===i} className={camera===i?'selected':''}><span>{cam.code}</span><b>{cam.label}</b><small>{cam.detail}</small></button>)}<a href="https://www.usgs.gov/volcanoes/kilauea/summit-webcams" target="_blank" rel="noreferrer">All official cameras and still images ↗</a></div></div></section>

    <ThermalView refreshAt={windowEnd}/>
    <TimeMachine/>
    <section className="learn" id="learn"><div><p className="kicker">Understanding forecasts</p><h2>Evidence improves awareness—not certainty.</h2><p>Scientists combine ground movement, earthquakes, gas, heat, and camera observations with past behavior. This tracker displays observations and official status; it does not generate a validated eruption forecast.</p></div><div className="forecastScale"><h3>A few words, made clearer</h3><p><b>Inflation</b><br/>The volcano’s ground deforms as conditions beneath it change.</p><p><b>Tremor</b><br/>Persistent ground vibration, different from a count of individual earthquakes.</p><p><b>Episode</b><br/>A burst of activity that can be part of a longer eruption.</p><a href={MONITORING_URL} target="_blank" rel="noreferrer">Learn from USGS monitoring guidance ↗</a></div></section>
    <section className="safety"><span aria-hidden="true">!</span><div><p className="kicker">When it matters</p><h2>Follow official safety guidance.</h2><p>Do not use this dashboard to decide whether an area is safe. Follow USGS HVO, park closures, Hawaiʻi County alerts, and air-quality guidance.</p></div><a href={NOTICE_URL} target="_blank" rel="noreferrer">Open USGS updates ↗</a></section>
    <footer className="footer"><div className="brand"><span className="brandMark">K</span><span>Kīlauea Watch</span></div><p>Independent dashboard · USGS data may be delayed, preliminary, or unavailable.</p><div><a href={MONITORING_URL} target="_blank" rel="noreferrer">Monitoring sources</a><a href="https://earthquake.usgs.gov/fdsnws/event/1/" target="_blank" rel="noreferrer">Catalog API</a></div></footer>
  </main>;
}
