import {useState} from 'react';
import {fmtTime,NOTICE_URL,type Status,type Quake,type Range} from './monitoring';
import {forecastExcerpt,compareWindows} from './briefing';

const thermalPage='https://www.usgs.gov/volcanoes/kilauea/f1cam-halemaumau-thermal-image-west-rim-summit-caldera-looking-southeast';
const thermalRoot='https://volcanoes.usgs.gov/observatories/hvo/cams/F1cam/images/';
export function Briefing({status,stale,quakes,quakeStale,range,start,end}:{status:Status|null;stale:boolean;quakes:Quake[]|null;quakeStale:boolean;range:Range;start:number;end:number}) {
  const forecast=status?forecastExcerpt(status.noticeSynopsis):null;
  const trend=quakes?compareWindows(quakes,start,end):null;
  return <section className="briefingSection" id="briefing" aria-labelledby="briefing-title">
    <div className="sectionTitle"><p className="kicker">Start here · a source-led briefing</p><h2 id="briefing-title">What’s happening—and what changed?</h2><p>A quick read of the latest HVO report and the earthquake window you selected. No AI forecast or invented probability.</p></div>
    <div className="briefingGrid">
      <article><p className="kicker">01 / Official report {stale?'· cached':''}</p><h3>What HVO is reporting</h3><p>{status?.noticeSynopsis||'The official report is not available yet. Open HVO directly for current conditions.'}</p><p className="sourceTime">Report timestamp: {status?fmtTime(status.alertDate):'Unavailable'}</p><a href={status?.noticeUrl||NOTICE_URL} target="_blank" rel="noreferrer">Read the full dated report ↗</a></article>
      <article><p className="kicker">02 / Observed counts {quakeStale?'· cached':''}</p><h3>{trend?`${trend.recent} vs ${trend.earlier} earthquakes`:'Waiting for earthquake data'}</h3><p>{trend?`There were ${trend.direction} recorded earthquakes in the newer half of the selected ${range.toLowerCase()} than in the older half. Both intervals are the same length.`:'No comparison is assumed while the catalog is unavailable.'}</p><p className="sourceTime">Window: {fmtTime(start)} – {fmtTime(end)}. Newer half starts {fmtTime(start+(end-start)/2)}.</p><p className="briefingCaution">This is a count comparison—not a prediction. Small counts, revised detections, and non-volcanic events can affect it.</p><a href="#activity">Explore the counts ↓</a></article>
      <article className="outlookCard"><p className="kicker">03 / Forecast context {stale?'· cached':''}</p><h3>What about the next episode?</h3><p>{forecast||'No forecast wording is available in the short summary. That does not mean HVO has issued no forecast—check the full notice.'}</p><p className="sourceTime">{forecast?'Exact forecast-related sentences from the report above.':'This dashboard does not infer a forecast window from alert colors or earthquake counts.'}</p><a href={status?.noticeUrl||NOTICE_URL} target="_blank" rel="noreferrer">Check HVO’s assessment ↗</a></article>
    </div>
  </section>;
}

export function ThermalView({refreshAt}:{refreshAt:number}) {
  const [replay,setReplay]=useState(false);
  const [retry,setRetry]=useState(0);
  return <section className="thermalSection" id="thermal" aria-labelledby="thermal-title">
    <div className="sectionTitle"><p className="kicker">A different kind of view · F1cam</p><h2 id="thermal-title">See the crater’s heat</h2><p>Real USGS thermal imagery from the west rim. Switch between the latest image and the official rolling replay.</p></div>
    <div className="thermalLayout"><article className="chartCard"><div className="mediaToolbar"><div className="ranges" aria-label="Thermal view"><button aria-pressed={!replay} className={!replay?'active':''} onClick={()=>setReplay(false)}>Latest image</button><button aria-pressed={replay} className={replay?'active':''} onClick={()=>setReplay(true)}>24-hour replay</button></div><button className="textButton" onClick={()=>setRetry(n=>n+1)}>Reload image</button></div>
      <ThermalImage key={`${replay}-${refreshAt}-${retry}`} url={`${thermalRoot}${replay?'F1cam.gif':'M.jpg'}?refresh=${Math.floor(refreshAt/300000)}-${retry}`} replay={replay}/>
      <p className="sourceTime">Observation time: read the timestamp printed on the image. Reload time is not measurement time. Gaps or an old final frame can indicate a camera outage.</p><a className="dataLink" href={thermalPage} target="_blank" rel="noreferrer">Official F1cam image and replay ↗</a>
    </article><aside className="thermalGuide"><h3>How to read this view</h3><ol><li><b>Read the color scale.</b> Colors represent the camera’s thermal measurements—not an eruption probability.</li><li><b>Check the time.</b> This is a periodically updated image, not a continuous video stream.</li><li><b>Compare carefully.</b> Scale changes, gas, clouds, and rain can change the appearance. A hotter-looking color alone does not prove temperatures rose.</li></ol><p>The replay animates only after you select it. Choose “Latest image” to stop the animation.</p><a href="https://www.usgs.gov/volcanoes/kilauea/maps" target="_blank" rel="noreferrer">Explore dated USGS thermal and lava maps ↗</a></aside></div>
  </section>;
}
function ThermalImage({url,replay}:{url:string;replay:boolean}) {
  const [state,setState]=useState('loading');
  return <div className="thermalImage"><span className="mediaLabel">{replay?'ROLLING REPLAY · NOT LIVE VIDEO':'LATEST USGS IMAGE'}</span>{state==='loading'&&<p role="status">Loading official thermal imagery…</p>}{state==='error'?<p role="status">The thermal image could not load. <a href={thermalPage} target="_blank" rel="noreferrer">Open the official camera ↗</a></p>:<a href={url} target="_blank" rel="noreferrer" aria-label="Open full-size thermal imagery"><img src={url} alt={`USGS F1cam ${replay?'24-hour thermal replay':'latest thermal image'} of Halemaʻumaʻu; temperature legend and observation timestamp are printed in the image`} onLoad={()=>setState('ready')} onError={()=>setState('error')}/></a>}</div>;
}

export const chapters=[
  {year:'2018',title:'The summit drops',date:'June 13 – July 7, 2018',view:'Keanakākoʻi Overlook · looking north',description:'Watch the caldera floor subside as magma withdrawal reduces support beneath the summit. The time-lapse captures part of the 2018 collapse—not present-day conditions.',youtube:'-5pHpsY9cp0',video:'',poster:'',source:'https://www.youtube.com/watch?v=-5pHpsY9cp0'},
  {year:'2024–25',title:'Lava fills the caldera',date:'Sequence begins December 2024 · published September 4, 2025',view:'B1cam · east rim',description:'Repeated lava-fountaining episodes add lava to the crater floor. Watch the changing landscape in this 32-second USGS sequence; use the player’s timeline to pause and compare frames.',youtube:'',video:'https://usgs-ocapsv2-public-output-media.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/media/video/b1cammovie/MP4/b1cammovie.mp4',poster:'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/styles/video_poster/public/media/images/20241220120002M_0.jpg?itok=nzYqlpSg',source:'https://www.usgs.gov/media/videos/timelapse-video-showing-filling-kaluapele-kilaueas-summit-caldera-a-result-episodic'},
  {year:'2026',title:'An episode in thermal vision',date:'August 25, 2026 · episode 54',view:'F1cam · northwest rim',description:'A thermal-camera replay of lava-fountaining episode 54. This is a dated historical recording, not an indication that lava is erupting now. Retain the original legend when comparing heat patterns.',youtube:'',video:'https://usgs-ocapsv2-public-output-media.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/media/video/vlc-record-2026-08-26-12h32m03s-F1cam20260825M.avi-/MP4/vlc-record-2026-08-26-12h32m03s-F1cam20260825M.avi-.mp4',poster:'https://d9-wret.s3.us-west-2.amazonaws.com/assets/palladium/production/s3fs-public/styles/video_poster/public/media/images/20260825120013M_%281%29.jpg?itok=TE3-ljTW',source:'https://www.usgs.gov/media/videos/august-25-2026-timelapse-video-kilauea-episode-54-lava-fountaining-f1cam'},
];
export function TimeMachine() {
  const [index,setIndex]=useState(1);
  const [play,setPlay]=useState(false);
  const [error,setError]=useState(false);
  const chapter=chapters[index];
  return <section className="historySection" id="history" aria-labelledby="history-title"><div className="sectionTitle"><p className="kicker">The crater time machine · real USGS recordings</p><h2 id="history-title">One crater. Remarkable change.</h2><p>Travel between three documented chapters. These are selected moments, not an uninterrupted record; viewpoints and time scales differ.</p></div>
    <div className="chapterPicker" aria-label="Choose a historical chapter">{chapters.map((c,i)=><button key={c.year} aria-pressed={index===i} onClick={()=>{setIndex(i);setPlay(false);setError(false);}} className={index===i?'selected':''}><span>{c.year}</span><b>{c.title}</b></button>)}</div>
    <div className="historyLayout"><div className="historyPlayer"><span className="mediaLabel">ARCHIVE · {chapter.year} · NOT LIVE</span>{error?<p role="status">This recording could not load. Use the official source link beside it.</p>:play?(chapter.youtube?<iframe src={`https://www.youtube.com/embed/${chapter.youtube}?autoplay=1&mute=1&rel=0`} title={chapter.title} referrerPolicy="strict-origin-when-cross-origin" allow="autoplay; encrypted-media; fullscreen; picture-in-picture" allowFullScreen/>:<video key={chapter.video} controls autoPlay muted playsInline preload="metadata" poster={chapter.poster} src={chapter.video} aria-label={chapter.title} onError={()=>setError(true)}/>):<div className="archiveCover">{chapter.poster&&<img src={chapter.poster} alt="Preview frame from the selected USGS archive recording" onError={e=>{e.currentTarget.style.display='none';}}/>}<button onClick={()=>setPlay(true)}>▶ Play {chapter.year} recording</button></div>}</div><article className="historyNotes" aria-live="polite"><p className="kicker">{chapter.date}</p><h3>{chapter.title}</h3><p>{chapter.description}</p><p className="sourceTime">Viewpoint: {chapter.view}<br/>Credit: USGS · public-domain footage.</p><a href={chapter.source} target="_blank" rel="noreferrer">Open original recording and description ↗</a>{play&&<button className="textButton" onClick={()=>setPlay(false)}>Stop recording</button>}</article></div>
    <p className="sourceTime">No AI-generated frames or invented transitions. Camera positions differ, so these views should not be used to measure crater growth against one another. <a href="https://www.usgs.gov/volcanoes/kilauea/multimedia/videos" target="_blank" rel="noreferrer">Browse newer videos and the full USGS archive ↗</a></p>
  </section>;
}
